---
- name: Copy nginx01 packages directory to hosts
  ansible.builtin.copy:
    src: files/nginx01
    dest: /tmp
    mode: 0755

- name: Install all .deb packages with dpkg
  ansible.builtin.shell:
    cmd: "dpkg -i *.deb"
    chdir: /tmp/nginx01


- name: Fix broken dependencies (equivalent of apt-get install -f)
  ansible.builtin.apt:
    state: fixed

- name: Create website directory
  ansible.builtin.file:
    path: /var/www/mysite
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'

- name: Deploy index.html
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/mysite/index.html
    mode: '0644'

- name: Deploy Nginx config
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/mysite
    mode: '0644'
  notify: reload nginx

- name: Enable site configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mysite
    dest: /etc/nginx/sites-enabled/mysite
    state: link
  notify: reload nginx